version: '3.8'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["serve", "-s", "dist", "-l", "3000"]
